
service: step-function
app: step-function
org: jatin07

frameworkVersion: '2'

custom:
  account: ${opt:account, 'Personal'}
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  
functions:
  first_lambda:
    handler: first_lambda.handler
    name: first_lambda_function_${self:provider.stage}
    description: LAMBDA TO BE CALLED FIRST IN STATEMACHINE
    memorySize: 256
    timeout: 900

  second_lambda:
    handler: second_lambda.handler
    name: second_lambda_function_${self:provider.stage}
    description: LAMBDA TO BE CALLED SECOND IN STATE MACHINE
    memorySize: 256
    timeout: 900 

  third_lambda:
    handler: third_lambda.handler
    name: third_lambda_function_${self:provider.stage}
    description: LAMBDA TO BE CALLED THIRD IN STATEMACHINE
    memorySize: 256
    timeout: 900 

stepFunctions:
  stateMachines:
    chaining-lambda-function-state-machine: ${file(chaining-lambda-function-state-machine.yml):stateMachine}

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions